name: Trigger auto deployment for reatazuretesting

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/reatazuretesting-AutoDeployTrigger-22116ae3-3683-45b8-aa05-afba1e0d55f3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.REATAZURETESTING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REATAZURETESTING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REATAZURETESTING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: alphabrioprecr.azurecr.io
          registryUsername: ${{ secrets.REATAZURETESTING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REATAZURETESTING_REGISTRY_PASSWORD }}
          containerAppName: reatazuretesting
          resourceGroup: alpha-brio-pre
          imageToBuild: alphabrioprecr.azurecr.io/reatazuretesting:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


